[package]
name = "smart-home-12"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smart-home-12"
path = "src/main.rs"

[lib]
crate-type = ["cdylib"]
name = "smart_lib_12"

[dependencies]
libc = "0.2.132"
