[workspace]
members = [
  "fizzbuzz",
  "patterns",
  "patterns-2",
  "smart-home-1",
  "smart-home-2",
  "smart-home-3",
  "smart-home-4",
  "smart-home-5",
  "smart-home-6",
  "smart-home-7",
  "smart-home-8",
  "smart-home-9",
  "smart-home-10",
  "smart-home-11",
  "smart-home-12"
]
