[package]
name = "smart-home-10"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smart-home-10"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
rocket = "0.5.0-rc.2"
thiserror = "1.0.32"
